/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import clinica.Consulta;
import servicos.ServicoSecretaria;
import java.util.List;
import clinica.Paciente;
import java.time.LocalDate;
/**
 *
 * @author Cliente
 */
public class ConsultaFrame extends javax.swing.JFrame {
    private final ServicoSecretaria servicoAtual;
    private Paciente pacienteAtual;
    private Consulta consultaAtual;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultaFrame.class.getName());

    /**
     * Creates new form ConsultaFrame
     * @param servicoAtual
     * @param consultaAtual
     */
    public ConsultaFrame(ServicoSecretaria servicoAtual, Paciente pacienteAtual, Consulta consultaAtual) {
        initComponents();
        this.servicoAtual = servicoAtual;
        this.pacienteAtual = pacienteAtual;
        this.consultaAtual = consultaAtual;
        carregaConsultaPaciente();
        if (this.consultaAtual != null) {
            
        }
    }
    // metodos auxiliares
    private void carregaConsultaPaciente() {
        consultas.removeAllItems();
        List<Consulta> consultasPaciente = servicoAtual.listarConsultas();
        
    }
    private void marcarCamposEditar() {
        int horaInt = consultaAtual.getHoras();
        String horaStr = String.valueOf(horaInt);
        horas.setText(horaStr);
        
        int minInt = consultaAtual.getMinutos();
        String minStr = String.valueOf(minInt);
        minutos.setText(minStr);
        
        LocalDate dataLD = consultaAtual.getData();
        data.setText(dataLD.toString());
        
        int idInt = consultaAtual.getPacienteId().getDadoIdentificacao();
        String idString = String.valueOf(idInt);
        pacientes.setSelectedItem(idString);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConsultaType = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        horas = new javax.swing.JTextField();
        minutos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        normal = new javax.swing.JRadioButton();
        retorno = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        concluir = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        data = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Editar/Cadastrar Consultas");

        jLabel2.setText("Data da Consulta:");

        jLabel3.setText("Horário da Consulta:");

        horas.setText("horas");

        minutos.setText("minutos");

        jLabel4.setText(":");

        jLabel6.setText("Tipo da Consulta:");

        ConsultaType.add(normal);
        normal.setText("Normal (1h)");
        normal.addActionListener(this::normalActionPerformed);

        ConsultaType.add(retorno);
        retorno.setText("Retorno (30min)");

        concluir.setText("Concluir");
        concluir.addActionListener(this::concluirActionPerformed);

        excluir.setBackground(new java.awt.Color(255, 0, 0));
        excluir.setText("Excluir dados");
        excluir.addActionListener(this::excluirActionPerformed);

        data.setText("dd/mm/aa");

        jLabel5.setText("ID da consulta para editar:");

        jTextField1.setText("insira o ID da consulta...");

        jLabel8.setText("(se quiser criar, deixe vazio)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(concluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(horas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(retorno)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(normal)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(normal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retorno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(concluir)
                    .addComponent(excluir))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void concluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirActionPerformed
        if (consultaAtual == null) {
            consultaAtual = new Consulta();
        }
        
        String dataInput = data.getText();
        LocalDate dataLD = LocalDate.parse(dataInput);
        String horasInput = horas.getText();
        int horasInt = Integer.parseInt(horasInput);
        String minInput = minutos.getText();
        int minInt = Integer.parseInt(minInput);
        String idPaciente = (String) pacientes.getSelectedItem();
        int idInt = Integer.parseInt(idPaciente);
        Paciente pacienteAtual = servicoAtual.buscaPaciente(idInt);
        consultaAtual.setData(dataLD);
        consultaAtual.setHoras(horasInt);
        consultaAtual.setMinutos(minInt);
        consultaAtual.setPacienteId(pacienteAtual);
        if (normal.isSelected()) {
            consultaAtual.setTipoConsulta("normal");
        } else if (retorno.isSelected()) {
            consultaAtual.setTipoConsulta("retorno");
        }
    }//GEN-LAST:event_concluirActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        VerificacaoExcluir VerificaDados = new VerificacaoExcluir(this, true);
        VerificaDados.setLocationRelativeTo(this);
        VerificaDados.setVisible(true);
        
        if(VerificaDados.isConfirmou()) {
            this.dispose();
            String idPaciente = (String) pacientes.getSelectedItem();
            int idInt = Integer.parseInt(idPaciente);
            servicoAtual.removerPaciente(idInt);
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_normalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultaFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ConsultaType;
    private javax.swing.JButton concluir;
    private javax.swing.JTextField data;
    private javax.swing.JButton excluir;
    private javax.swing.JTextField horas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField minutos;
    private javax.swing.JRadioButton normal;
    private javax.swing.JRadioButton retorno;
    // End of variables declaration//GEN-END:variables
}
