/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import clinica.DadosAdicionaisPaciente;
import clinica.Paciente;

/**
 *
 * @author Cliente
 */
public class DadosAdicionaisFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DadosAdicionaisFrame.class.getName());
    private DadosAdicionaisPaciente dados;
    
    /**
     * Creates new form DadosAdicionaisFrame
     * @param dados
     */
    public DadosAdicionaisFrame(DadosAdicionaisPaciente dados) {
        this.dados = dados;
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        concluir = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        excluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dados Adicionais do Paciente");

        jCheckBox1.setText("Fuma com frequência");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCheckBox1MousePressed(evt);
            }
        });

        jCheckBox2.setText("Bebe bebidas alcoólicas com frequência");
        jCheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCheckBox2MousePressed(evt);
            }
        });

        jCheckBox3.setText("Possui colesterol");
        jCheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCheckBox3MousePressed(evt);
            }
        });

        jCheckBox4.setText("Possui diabetes");
        jCheckBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCheckBox4MousePressed(evt);
            }
        });

        jCheckBox5.setText("Possui doença(s) cardíaca(s)");
        jCheckBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCheckBox5MousePressed(evt);
            }
        });

        jTextField1.setText("insira Cirurgias...");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jCheckBox6.setText("Cirurgia(s) feita(s) (se marcado, especificar)");
        jCheckBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCheckBox6MousePressed(evt);
            }
        });

        jCheckBox7.setText("Alergia(s) (se marcado, especificar)");
        jCheckBox7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCheckBox7MousePressed(evt);
            }
        });

        jTextField2.setText("insira Alergias...");

        concluir.setText("Concluir");
        concluir.addActionListener(this::concluirActionPerformed);

        excluir.setBackground(new java.awt.Color(255, 0, 0));
        excluir.setText("Excluir dados");
        excluir.addActionListener(this::excluirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(concluir)
                        .addGap(24, 24, 24))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox3)
                                    .addComponent(jCheckBox4)
                                    .addComponent(jCheckBox5)
                                    .addComponent(jCheckBox6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jCheckBox7))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(concluir)
                    .addComponent(excluir))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void concluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            dados.setFuma(true);
        }
        else{
            dados.setFuma(false);
        }
        
        if(jCheckBox2.isSelected()){
            dados.setBebe(true);
        }
        else{
            dados.setBebe(false);
        }
        
        if(jCheckBox3.isSelected()){
            dados.setColesterol(true);
        }
        else{
            dados.setColesterol(false);
        }
        
        if(jCheckBox4.isSelected()){
            dados.setDiabetes(true);
        }
        else{
            dados.setDiabetes(false);
        }
        
        if(jCheckBox5.isSelected()){
            dados.setDoencaCardiaca(true);
        }
        else{
            dados.setDoencaCardiaca(false);
        }
        
        if(jCheckBox6.isSelected()){
            String cirurgias = jTextField1.getText();
            dados.setCirurgias(cirurgias);
        }
        
        if(jCheckBox7.isSelected()){
            String alergias = jTextField2.getText();
            dados.setAlergias(alergias);
        }
        
        this.dispose();
    }//GEN-LAST:event_concluirActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        VerificacaoExcluir VerificaDados = new VerificacaoExcluir(this, true);
        VerificaDados.setLocationRelativeTo(this);
        VerificaDados.setVisible(true);
        
        if(VerificaDados.isConfirmou()) {
            this.dispose();
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void jCheckBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox2MouseClicked
        // TODO add your handling code here:
        if(jCheckBox2.isSelected()){
            jCheckBox2.setSelected(false);
        }
        else{
            jCheckBox2.setSelected(true);
        }
    }//GEN-LAST:event_jCheckBox2MouseClicked

    private void jCheckBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox3MouseClicked
        // TODO add your handling code here:
        if(jCheckBox3.isSelected()){
            jCheckBox3.setSelected(false);
        }
        else{
            jCheckBox3.setSelected(true);
        }
    }//GEN-LAST:event_jCheckBox3MouseClicked

    private void jCheckBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox4MouseClicked
        // TODO add your handling code here:
        if(jCheckBox4.isSelected()){
            jCheckBox4.setSelected(false);
        }
        else{
            jCheckBox4.setSelected(true);
        }
    }//GEN-LAST:event_jCheckBox4MouseClicked

    private void jCheckBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox5MouseClicked
        // TODO add your handling code here:
        if(jCheckBox5.isSelected()){
            jCheckBox5.setSelected(false); 
        }
        else{
            jCheckBox5.setSelected(true);
        }
    }//GEN-LAST:event_jCheckBox5MouseClicked

    private void jCheckBox6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox6MouseClicked
        // TODO add your handling code here:
        if(jCheckBox6.isSelected()){
            jCheckBox6.setSelected(false); 
        }
        else{
            jCheckBox6.setSelected(true);
        }
    }//GEN-LAST:event_jCheckBox6MouseClicked

    private void jCheckBox7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox7MouseClicked
        // TODO add your handling code here:
        if(jCheckBox7.isSelected()){
            jCheckBox7.setSelected(false);   
        }
        else{
            jCheckBox7.setSelected(true);
        }
    }//GEN-LAST:event_jCheckBox7MouseClicked

    private void jCheckBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MousePressed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected() == true){
            jCheckBox1.setSelected(false);
        }
        else{
            jCheckBox1.setSelected(true);
        }
    }//GEN-LAST:event_jCheckBox1MousePressed

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        // TODO add your handling code here:
        if(jCheckBox1.isSelected() == true){
            jCheckBox1.setSelected(false);
        }
        else{
            jCheckBox1.setSelected(true);
        }
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jCheckBox2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox2MousePressed
        // TODO add your handling code here:
        if(jCheckBox2.isSelected()){
            jCheckBox2.setSelected(false);
        }
        else{
            jCheckBox2.setSelected(true);
        }
    }//GEN-LAST:event_jCheckBox2MousePressed

    private void jCheckBox3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox3MousePressed
        // TODO add your handling code here:
        if(jCheckBox3.isSelected()){
            jCheckBox3.setSelected(false);
        }
        else{
            jCheckBox3.setSelected(true);
        }
    }//GEN-LAST:event_jCheckBox3MousePressed

    private void jCheckBox4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox4MousePressed
        // TODO add your handling code here:
        if(jCheckBox4.isSelected()){
            jCheckBox4.setSelected(false);
        }
        else{
            jCheckBox4.setSelected(true);
        }
    }//GEN-LAST:event_jCheckBox4MousePressed

    private void jCheckBox5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox5MousePressed
        // TODO add your handling code here:
        if(jCheckBox5.isSelected()){
            jCheckBox5.setSelected(false);   
        }
        else{
            jCheckBox5.setSelected(true);
        }
    }//GEN-LAST:event_jCheckBox5MousePressed

    private void jCheckBox6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox6MousePressed
        // TODO add your handling code here:
        if(jCheckBox6.isSelected()){
            jCheckBox6.setSelected(false);   
        }
        else{
            jCheckBox6.setSelected(true);
        }
    }//GEN-LAST:event_jCheckBox6MousePressed

    private void jCheckBox7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox7MousePressed
        // TODO add your handling code here:
        if(jCheckBox7.isSelected()){
            jCheckBox7.setSelected(false);   
        }
        else{
            jCheckBox7.setSelected(true);
        }
    }//GEN-LAST:event_jCheckBox7MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Paciente p1 = new Paciente();
        DadosAdicionaisPaciente dadosAdicionais = new DadosAdicionaisPaciente(p1, false, false, false, false, false, "Nenhuma", "Nenhuma");

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DadosAdicionaisFrame(dadosAdicionais).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton concluir;
    private javax.swing.JButton excluir;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
