/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import clinica.Prontuario;
import servicos.ServicoMedico;

/**
 *
 * @author Cliente
 */
public class ProntuarioFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProntuarioFrame.class.getName());
    private int idPaciente;
    private ServicoMedico medico;
    
    /**
     * Creates new form ProntuarioFrame
     * @param id
     * @param medico
     */
    public ProntuarioFrame(int id, ServicoMedico medico) {
        initComponents();
        this.idPaciente = id;
        this.medico = medico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sintomas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        diagnostico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        prescricao = new javax.swing.JTextField();
        concluir = new javax.swing.JButton();
        excluirDados = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Prontuário do Paciente");

        jLabel2.setText("Sintomas:");

        sintomas.setText("insira Sintomas...");

        jLabel3.setText("Diagnóstico:");

        diagnostico.setText("insira Diagnóstico...");

        jLabel4.setText("Prescrição médica:");

        prescricao.setText("insira Prescrição...");

        concluir.setText("Concluir");
        concluir.addActionListener(this::concluirActionPerformed);

        excluirDados.setBackground(new java.awt.Color(255, 0, 0));
        excluirDados.setText("Excluir dados");
        excluirDados.addActionListener(this::excluirDadosActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(sintomas)
                            .addComponent(jLabel3)
                            .addComponent(diagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(prescricao))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 138, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(excluirDados)
                                .addGap(18, 18, 18)))
                        .addComponent(concluir)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sintomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jSeparator1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(concluir)
                    .addComponent(excluirDados))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluirDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirDadosActionPerformed
        VerificacaoExcluir VerificaPront = new VerificacaoExcluir(this, true);
        VerificaPront.setLocationRelativeTo(this);
        VerificaPront.setVisible(true);
        
        if(VerificaPront.isConfirmou()) {
            //servicoMedico.removeDadosAdicionais(dados);
            this.dispose();
        }
    }//GEN-LAST:event_excluirDadosActionPerformed

    private void concluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirActionPerformed
        // TODO add your handling code here:
        String sintomasPaciente = sintomas.getText();
        String diagnosticoProntuario = diagnostico.getText();
        String prescricaoProntuario = prescricao.getText();
        Prontuario novoProntuario = new Prontuario(idPaciente,sintomasPaciente, diagnosticoProntuario, prescricaoProntuario);
        
        if(medico.buscaProntuario(idPaciente) != null){
            medico.atualizaProntuario(novoProntuario);
        }
        else{
            medico.cadastraProntuario(novoProntuario);
        }
    }//GEN-LAST:event_concluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        ServicoMedico medico = new ServicoMedico();
        int id = 1;

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProntuarioFrame(id, medico).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton concluir;
    private javax.swing.JTextField diagnostico;
    private javax.swing.JButton excluirDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField prescricao;
    private javax.swing.JTextField sintomas;
    // End of variables declaration//GEN-END:variables
}
