/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import clinica.Consulta;
import clinica.Paciente;
import java.util.List;
import servicos.ServicoSecretaria;

/**
 *
 * @author Cliente
 */
public class ServSecretFrame extends javax.swing.JFrame {
    private ServicoSecretaria servicoAtual;
    private Consulta consultaAtual;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServSecretFrame.class.getName());

    /**
     * Creates new form SecretariaServFrame
     */
    public ServSecretFrame() {
        initComponents();
        setVisible(true);
    }
    private void carregaPacientesComboBox() {
        pacientes.removeAllItems();
        List<Paciente> listaPacientes = servicoAtual.listarPacientes();
        for (Paciente p: listaPacientes) {
            String idString = String.valueOf(p.getDadoIdentificacao());
            pacientes.addItem(idString); //só vai exibir o id dos pacientes. depois, no botão de concluir, deve procurar no BD o paciente a partir do id
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escolha = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dadosPaciente = new javax.swing.JRadioButton();
        consulta = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        relatorio = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Serviço Secretário");

        jLabel2.setText("Gerenciar:");

        escolha.add(dadosPaciente);
        dadosPaciente.setText("Gerenciar dados de um paciente");

        escolha.add(consulta);
        consulta.setText("Gerenciar Consultas");

        jLabel3.setText("Gerar:");

        escolha.add(relatorio);
        relatorio.setText("Gerar Relatório de Consulta");

        jLabel4.setText("ID do Paciente em que queira gerenciar os dados:");

        ok.setText("OK");
        ok.addActionListener(this::okActionPerformed);

        jTextField1.setText("insira o Id...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1)
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(consulta)
                                    .addComponent(jLabel3)
                                    .addComponent(relatorio)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dadosPaciente)))
                                .addGap(0, 76, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dadosPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(relatorio)
                .addGap(31, 31, 31)
                .addComponent(ok)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        if(dadosPaciente.isSelected()) { //se o botão de gerenciar dados do paciente está acionada
            if(criarPaciente.isSelected()) { //para criar os dados de um paciente
                PacienteFrame novoPacienteFrame = new PacienteFrame(servicoAtual, null);
                novoPacienteFrame.setVisible(true);
            } else { //para editar os dados de um paciente
            String idPaciente = (String) pacientes.getSelectedItem();
            if (idPaciente == null) {
                return;
            }
            int idInt = Integer.parseInt(idPaciente);
            Paciente pacienteAtual = servicoAtual.buscaPaciente(idInt);
            PacienteFrame editarPacienteFrame = new PacienteFrame(servicoAtual, pacienteAtual);
            editarPacienteFrame.setVisible(true);
            } 
        } else if (consulta.isSelected()) { //se o botão de gerenciar consultas está acionado
            ConsultaFrame consultaFrame = new ConsultaFrame(servicoAtual, )
        }
    }//GEN-LAST:event_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ServSecretFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton consulta;
    private javax.swing.JRadioButton dadosPaciente;
    private javax.swing.ButtonGroup escolha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton ok;
    private javax.swing.JRadioButton relatorio;
    // End of variables declaration//GEN-END:variables

}
