/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import servicos.ServicoMedico;
import clinica.Paciente;
import javax.swing.JOptionPane;
import clinica.DadosAdicionaisPaciente;

/**
 *
 * @author Cliente
 */
public class ServMedicFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServMedicFrame.class.getName());

    /**
     * Creates new form MedicoServFrame
     */
    public ServMedicFrame() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escolha = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dadosAdicionais = new javax.swing.JRadioButton();
        Prontuario = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        Relatorio = new javax.swing.JRadioButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Serviço Médico");

        jLabel2.setText("Gerenciar:");

        Escolha.add(dadosAdicionais);
        dadosAdicionais.setText("Gerenciar Dados Adicionais do paciente");
        dadosAdicionais.addActionListener(this::dadosAdicionaisActionPerformed);

        Escolha.add(Prontuario);
        Prontuario.setText("Gerenciar Prontuários do paciente");
        Prontuario.addActionListener(this::ProntuarioActionPerformed);

        jLabel3.setText("Gerar:");

        Escolha.add(Relatorio);
        Relatorio.setText("Gerar Relatório");

        jToggleButton1.setText("OK");
        jToggleButton1.addActionListener(this::jToggleButton1ActionPerformed);

        jLabel4.setText("ID do Paciente em que queira gerenciar os dados:");

        jTextField1.setText("insira o ID...");

        jLabel5.setText("(inserir um número válido)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(139, 139, 139))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(dadosAdicionais)
                            .addComponent(jLabel3)
                            .addComponent(Relatorio)
                            .addComponent(Prontuario)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dadosAdicionais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Prontuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Relatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton1)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dadosAdicionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadosAdicionaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dadosAdicionaisActionPerformed

    private void ProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProntuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProntuarioActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        ServicoMedico medico = new ServicoMedico();
        String idPaciente = jTextField1.getText();
            int id = Integer.parseInt(idPaciente);
            Paciente paciente = medico.buscaPaciente(id);

            if(paciente != null){
                if(Relatorio.isSelected()){
                    String nomePaciente = medico.buscaPaciente(id).getNome();
                    RelatorioMedicoFrame relatorio = new RelatorioMedicoFrame(nomePaciente);
                    this.dispose();
                }
                else{
                    if(dadosAdicionais.isSelected()){
                        DadosAdicionaisPaciente dados = medico.buscaDadosAdicionais(id);
                        DadosAdicionaisFrame frame = new DadosAdicionaisFrame(dados, medico);
                        this.dispose();
                    }
                    else{
                        if(Prontuario.isSelected()){
                            ProntuarioFrame frame = new ProntuarioFrame(id, medico);
                            this.dispose();
                        }
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Id não encontrado!");
            }       
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ServMedicFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Escolha;
    private javax.swing.JRadioButton Prontuario;
    private javax.swing.JRadioButton Relatorio;
    private javax.swing.JRadioButton dadosAdicionais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
