/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import clinica.Consulta;
import clinica.Paciente;
import java.util.List;
import javax.swing.JOptionPane;
import servicos.ServicoSecretaria;

/**
 *
 * @author Cliente
 */
public class ServSecretFrame extends javax.swing.JFrame {
    private ServicoSecretaria servicoAtual;
    private Consulta consultaAtual;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServSecretFrame.class.getName());

    /**
     * Creates new form SecretariaServFrame
     */
    public ServSecretFrame() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escolha = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dadosPaciente = new javax.swing.JRadioButton();
        consulta = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        relatorio = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Serviço Secretário");

        jLabel2.setText("Gerenciar:");

        escolha.add(dadosPaciente);
        dadosPaciente.setText("Gerenciar dados de um paciente");

        escolha.add(consulta);
        consulta.setText("Gerenciar Consultas");

        jLabel3.setText("Gerar:");

        escolha.add(relatorio);
        relatorio.setText("Gerar Relatório de Consulta");

        jLabel4.setText("ID do Paciente em que queira gerenciar os dados:");

        ok.setText("OK");
        ok.addActionListener(this::okActionPerformed);

        jTextField1.setText("insira o Id...");

        jLabel5.setText("(Se quiser criar, digite 0)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(consulta)
                            .addComponent(relatorio)
                            .addComponent(dadosPaciente)
                            .addComponent(jLabel3))
                        .addGap(0, 133, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dadosPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(relatorio)
                .addGap(36, 36, 36)
                .addComponent(ok)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        if(dadosPaciente.isSelected()) {    
            try {
                // Pega o texto do campo de texto e remove espaços em branco
                String idTexto = jTextField1.getText().trim();

                // Se o usuário não digitou nada ou manteve o texto padrão, assume 0 (Criar)
                if (idTexto.isEmpty() || idTexto.equals("insira o Id...")) {
                    idTexto = "0";
                }

                int idInt = Integer.parseInt(idTexto);

                if (idInt == 0) { // Para criar os dados de um novo paciente (Se digitar 0)
                    PacienteFrame novoPacienteFrame = new PacienteFrame(servicoAtual, null);
                    novoPacienteFrame.setLocationRelativeTo(null);
                    novoPacienteFrame.setVisible(true);
                } else { // Para editar os dados de um paciente existente
                    Paciente pacienteAtual = servicoAtual.buscaPaciente(idInt);
                    if (pacienteAtual == null) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Paciente com ID " + idInt + " não encontrado no sistema.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    PacienteFrame editarPacienteFrame = new PacienteFrame(servicoAtual, pacienteAtual);
                    editarPacienteFrame.setLocationRelativeTo(null);
                    editarPacienteFrame.setVisible(true);
                }
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, insira um número de ID válido ou 0 para criar.", "Erro de Entrada", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } else if (consulta.isSelected()) { // Se o botão de gerenciar consultas está acionado
            ConsultaFrame consultaFrame = new ConsultaFrame(servicoAtual);
            consultaFrame.setLocationRelativeTo(null);
            consultaFrame.setVisible(true);

        } else if (relatorio.isSelected()) {
            // Precisa passar o servicoAtual para que a tela de relatório consiga buscar os dados
            RelatorioSecretariaFrame relatorioFrame = new RelatorioSecretariaFrame(this.servicoAtual);
            relatorioFrame.setLocationRelativeTo(null);
            relatorioFrame.setVisible(true);
        }
        /*if(dadosPaciente.isSelected()) { //se o botão de gerenciar dados do paciente está acionada
            if(jTextField1.getText().equals("")) { 
                JOptionPane.showMessageDialog(this, "Voce deve preencher o campo acima!");
                return;
            }
        String idPaciente = jTextField1.getText();
        int idInt = Integer.parseInt(idPaciente);
        if (dadosPaciente.isSelected()) {
            if (idInt == 0) { //cria um novo paciente
                PacienteFrame novoPacienteFrame = new PacienteFrame(servicoAtual, null);
                novoPacienteFrame.setVisible(true);
            } else { //para editar os dados de um paciente existente
                Paciente pacienteAtual = servicoAtual.buscaPaciente(idInt);
                if (pacienteAtual != null) { 
                    PacienteFrame atualizarPacienteFrame = new PacienteFrame(servicoAtual, null);
                    atualizarPacienteFrame.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Paciente não encontrado!");
                }
            }
        } else if (consulta.isSelected()) { //se o botão de gerenciar consultas está acionado
            if (idInt == 0) { //a verificação barra se o ID do paciente encolvido com a consulta for inválido
                JOptionPane.showMessageDialog(this, "Insira um ID válido!");
            } else {
                Paciente pacienteAtual = servicoAtual.buscaPaciente(idInt);
                if (pacienteAtual != null) {
                    ConsultaFrame consultaFrame = new ConsultaFrame(servicoAtual, pacienteAtual);
                }
            }
        }*/
        
    }//GEN-LAST:event_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ServSecretFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton consulta;
    private javax.swing.JRadioButton dadosPaciente;
    private javax.swing.ButtonGroup escolha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton ok;
    private javax.swing.JRadioButton relatorio;
    // End of variables declaration//GEN-END:variables

}
